exports.data = [
    {title: 'Apple', content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa ',  image: 'http://juliandance.org/wp-content/uploads/2016/01/RedApple.jpg'},
    {title: 'Orange', content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa ',  image: 'https://www.oasis-botanical.ca/wp-content/uploads/2017/02/orange-web.jpg'},
    {title: 'Grape', content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa ',  image: 'http://www.welchs.com/themes/welchs/build/images/grapes--promo.png'},
    {title: 'Rice', content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa ',  image: 'https://search.chow.com/thumbnail/640/0/www.chowstatic.com/assets/2014/09/27496_basic_steamed_rice_3000.jpg'},
    {title: 'Coffee', content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa ',  image: 'https://financialtribune.com/sites/default/files/field/image/17january/04-ff-coffee_120-ab.jpg'},
    {
        title: 'Sugar', 
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa ', 
        image: 'https://mydailymagazine.com/wp-content/uploads/2017/04/surprising-food-sugar-1492128642445.jpg'
    },
    {title: 'Apple', content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa ',  image: 'http://juliandance.org/wp-content/uploads/2016/01/RedApple.jpg'},
    {title: 'Orange', content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa ',  image: 'https://www.oasis-botanical.ca/wp-content/uploads/2017/02/orange-web.jpg'},
    {title: 'Grape', content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa ',  image: 'http://www.welchs.com/themes/welchs/build/images/grapes--promo.png'},
    {title: 'Rice', content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa ',  image: 'https://search.chow.com/thumbnail/640/0/www.chowstatic.com/assets/2014/09/27496_basic_steamed_rice_3000.jpg'},
    {title: 'Coffee', content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa ',  image: 'https://financialtribune.com/sites/default/files/field/image/17january/04-ff-coffee_120-ab.jpg'},
    {
        title: 'Sugar', 
        content:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu purus vestibulum, molestie libero nec, placerat tortor. Nulla at massa ', 
        image: 'https://mydailymagazine.com/wp-content/uploads/2017/04/surprising-food-sugar-1492128642445.jpg'
    },
];